defaults
{
    instances       = 300
    per_source      = UNLIMITED
    cps             = 0 0
    log_type        = FILE /proc/1/fd/1
    log_on_success  =
    log_on_failure  =
}

includedir /etc/xinetd.d